[package]
name = "chain_natives"
version = "0.1.0"
authors = ["zhuyingjie"]
edition = "2018"

[dependencies]
jni = { version = "0.19.0" }
libsm = { path = "../libsm" }
num-bigint = { version = "0.4", default-features = false }
mlsag = { path = "../mlsag" }
[lib]
crate_type = ["cdylib"]